/**
 * Tabela Pontaltech — preservada idêntica ao sms_monitor.py original.
 * 57 códigos cobrindo status (0-99), erros de operadora, screening, etc.
 */
import type { ErrorInfo } from "./sinch-codes";

export const PONTAL_CODES: Record<number, ErrorInfo> = {
  0: {cls: "STATUS", title: "Mensagem aceita — aguardando agendamento", title_en: "Message accepted, awaiting scheduling", desc: "Message accepted, awaiting scheduling", desc_pt: "Mensagem aceita — aguardando agendamento", type: "Temporary"},
  1: {cls: "STATUS", title: "Mensagem agendada", title_en: "Message scheduled", desc: "Message scheduled", desc_pt: "Mensagem agendada", type: "Temporary"},
  2: {cls: "STATUS", title: "Mensagem enviada para operadora", title_en: "Message sent to carrier", desc: "Message sent to carrier", desc_pt: "Mensagem enviada para operadora", type: "Temporary"},
  3: {cls: "STATUS", title: "Confirmação de envio pela operadora", title_en: "Send confirmed by carrier", desc: "Send confirmed by carrier", desc_pt: "Confirmação de envio pela operadora", type: "Temporary"},
  4: {cls: "CARRIER", title: "Erro no envio pela operadora", title_en: "Send error from carrier", desc: "Send error from carrier", desc_pt: "Erro no envio pela operadora", type: "Temporary"},
  5: {cls: "STATUS", title: "Confirmação de entrega pela operadora", title_en: "Delivery confirmed by carrier", desc: "Delivery confirmed by carrier", desc_pt: "Confirmação de entrega pela operadora", type: "Temporary"},
  6: {cls: "CARRIER", title: "Erro na entrega pela operadora", title_en: "Delivery error from carrier", desc: "Delivery error from carrier", desc_pt: "Erro na entrega pela operadora", type: "Temporary"},
  7: {cls: "SCREENING", title: "Mensagem bloqueada", title_en: "Message blocked", desc: "Message blocked", desc_pt: "Mensagem bloqueada", type: "Permanent"},
  8: {cls: "VALIDATION", title: "Mensagem inválida", title_en: "Invalid message", desc: "Invalid message", desc_pt: "Mensagem inválida", type: "Permanent"},
  9: {cls: "CANCELLED", title: "Mensagem cancelada", title_en: "Message cancelled", desc: "Message cancelled", desc_pt: "Mensagem cancelada", type: "Permanent"},
  10: {cls: "CARRIER", title: "Erro genérico", title_en: "Generic error", desc: "Generic error", desc_pt: "Erro genérico", type: "Temporary"},
  11: {cls: "ACCOUNT", title: "Sem crédito", title_en: "No credit", desc: "No credit", desc_pt: "Sem crédito", type: "Permanent"},
  12: {cls: "CARRIER", title: "Mensagem não entregue", title_en: "Message not delivered", desc: "Message not delivered", desc_pt: "Mensagem não entregue", type: "Temporary"},
  13: {cls: "CARRIER", title: "Mensagem expirada", title_en: "Message expired", desc: "Message expired", desc_pt: "Mensagem expirada", type: "Permanent"},
  14: {cls: "SCREENING", title: "Bloqueada na base de números inválidos", title_en: "Blocked — number in invalid base", desc: "Blocked — number in invalid base", desc_pt: "Bloqueada na base de números inválidos", type: "Permanent"},
  18: {cls: "SCREENING", title: "Bloqueada pela blacklist", title_en: "Blocked by blacklist", desc: "Blocked by blacklist", desc_pt: "Bloqueada pela blacklist", type: "Permanent"},
  19: {cls: "SCREENING", title: "Em recência — limite de frequência diário", title_en: "Daily frequency cap (recência)", desc: "Daily frequency cap (recência)", desc_pt: "Em recência — limite de frequência diário", type: "Temporary"},
  29: {cls: "STATUS", title: "Mensagem pausada", title_en: "Message paused", desc: "Message paused", desc_pt: "Mensagem pausada", type: "Temporary"},
  30: {cls: "STATUS", title: "Mensagem lida pelo usuário (apenas RCS)", title_en: "Message read by user (RCS only)", desc: "Message read by user (RCS only)", desc_pt: "Mensagem lida pelo usuário (apenas RCS)", type: "Temporary"},
  34: {cls: "CARRIER", title: "Exceção (apenas RCS)", title_en: "Exception (RCS only)", desc: "Exception (RCS only)", desc_pt: "Exceção (apenas RCS)", type: "Temporary"},
  74: {cls: "ACCOUNT", title: "Limite mensal excedido", title_en: "Monthly limit exceeded", desc: "Monthly limit exceeded", desc_pt: "Limite mensal excedido", type: "Permanent"},
  99: {cls: "STATUS", title: "Mensagem em preparação", title_en: "Message in preparation", desc: "Message in preparation", desc_pt: "Mensagem em preparação", type: "Temporary"},
  100: {cls: "VALIDATION", title: "Número inválido", title_en: "Invalid number", desc: "Invalid number", desc_pt: "Número inválido", type: "Permanent"},
  101: {cls: "VALIDATION", title: "Número de 11 dígitos inválido", title_en: "Invalid 11-digit number", desc: "Invalid 11-digit number", desc_pt: "Número de 11 dígitos inválido", type: "Permanent"},
  102: {cls: "VALIDATION", title: "Número de 10 dígitos inválido", title_en: "Invalid 10-digit number", desc: "Invalid 10-digit number", desc_pt: "Número de 10 dígitos inválido", type: "Permanent"},
  103: {cls: "VALIDATION", title: "DDD inválido", title_en: "Invalid area code (DDD)", desc: "Invalid area code (DDD)", desc_pt: "DDD inválido", type: "Permanent"},
  104: {cls: "VALIDATION", title: "Mensagem com mais de 160 caracteres (envio short)", title_en: "Message exceeds 160 chars (short SMS)", desc: "Message exceeds 160 chars (short SMS)", desc_pt: "Mensagem com mais de 160 caracteres (envio short)", type: "Permanent"},
  105: {cls: "VALIDATION", title: "Mensagem vazia", title_en: "Empty message", desc: "Empty message", desc_pt: "Mensagem vazia", type: "Permanent"},
  106: {cls: "VALIDATION", title: "Conteúdo do objeto não é um array válido (envio múltiplo)", title_en: "Object content is not a valid array (multi-send)", desc: "Object content is not a valid array (multi-send)", desc_pt: "Conteúdo do objeto não é um array válido (envio múltiplo)", type: "Permanent"},
  107: {cls: "VALIDATION", title: "Mensagem vazia", title_en: "Empty message", desc: "Empty message", desc_pt: "Mensagem vazia", type: "Permanent"},
  108: {cls: "VALIDATION", title: "Referência com mais de 50 caracteres", title_en: "Reference exceeds 50 characters", desc: "Reference exceeds 50 characters", desc_pt: "Referência com mais de 50 caracteres", type: "Permanent"},
  109: {cls: "VALIDATION", title: "Data de agendamento inválida", title_en: "Invalid scheduling date", desc: "Invalid scheduling date", desc_pt: "Data de agendamento inválida", type: "Permanent"},
  110: {cls: "VALIDATION", title: "Data inválida", title_en: "Invalid date", desc: "Invalid date", desc_pt: "Data inválida", type: "Permanent"},
  111: {cls: "VALIDATION", title: "Período inválido", title_en: "Invalid period", desc: "Invalid period", desc_pt: "Período inválido", type: "Permanent"},
  112: {cls: "VALIDATION", title: "Identificador inválido", title_en: "Invalid identifier", desc: "Invalid identifier", desc_pt: "Identificador inválido", type: "Permanent"},
  113: {cls: "VALIDATION", title: "URL inválido", title_en: "Invalid URL", desc: "Invalid URL", desc_pt: "URL inválido", type: "Permanent"},
  114: {cls: "ACCOUNT", title: "Conta sem crédito suficiente", title_en: "Insufficient account credit", desc: "Insufficient account credit", desc_pt: "Conta sem crédito suficiente", type: "Permanent"},
  115: {cls: "ACCOUNT", title: "Conta inválida", title_en: "Invalid account", desc: "Invalid account", desc_pt: "Conta inválida", type: "Permanent"},
  116: {cls: "VALIDATION", title: "Referência inválida", title_en: "Invalid reference", desc: "Invalid reference", desc_pt: "Referência inválida", type: "Permanent"},
  118: {cls: "ACCOUNT", title: "Flash SMS não autorizado", title_en: "Flash SMS not authorized", desc: "Flash SMS not authorized", desc_pt: "Flash SMS não autorizado", type: "Permanent"},
  198: {cls: "SCREENING", title: "Em recência mensal", title_en: "Monthly frequency cap (recência mensal)", desc: "Monthly frequency cap (recência mensal)", desc_pt: "Em recência mensal", type: "Permanent"},
  400: {cls: "VALIDATION", title: "Body inválido (HTTP 400)", title_en: "Bad request — invalid body", desc: "Bad request — invalid body", desc_pt: "Body inválido (HTTP 400)", type: "Permanent"},
  401: {cls: "AUTH", title: "Credenciais inválidas (HTTP 401)", title_en: "Invalid credentials", desc: "Invalid credentials", desc_pt: "Credenciais inválidas (HTTP 401)", type: "Permanent"},
  500: {cls: "INTERNAL", title: "Erro interno na requisição (HTTP 500)", title_en: "Internal server error on request", desc: "Internal server error on request", desc_pt: "Erro interno na requisição (HTTP 500)", type: "Temporary"},
  1000: {cls: "INTERNAL", title: "Não foi possível registrar a requisição", title_en: "Could not register request", desc: "Could not register request", desc_pt: "Não foi possível registrar a requisição", type: "Temporary"},
  1001: {cls: "INTERNAL", title: "Não foi possível criar a mensagem", title_en: "Could not create message", desc: "Could not create message", desc_pt: "Não foi possível criar a mensagem", type: "Temporary"},
  1002: {cls: "INTERNAL", title: "Não foi possível retornar a mensagem", title_en: "Could not return message", desc: "Could not return message", desc_pt: "Não foi possível retornar a mensagem", type: "Temporary"},
  1003: {cls: "INTERNAL", title: "Não foi possível criar a mensagem", title_en: "Could not create message", desc: "Could not create message", desc_pt: "Não foi possível criar a mensagem", type: "Temporary"},
  1004: {cls: "INTERNAL", title: "Não foi possível criar as mensagens", title_en: "Could not create messages", desc: "Could not create messages", desc_pt: "Não foi possível criar as mensagens", type: "Temporary"},
  1005: {cls: "INTERNAL", title: "Não foi possível retornar as mensagens", title_en: "Could not return messages", desc: "Could not return messages", desc_pt: "Não foi possível retornar as mensagens", type: "Temporary"},
  1006: {cls: "INTERNAL", title: "Não foi possível criar as mensagens", title_en: "Could not create messages", desc: "Could not create messages", desc_pt: "Não foi possível criar as mensagens", type: "Temporary"},
  1007: {cls: "INTERNAL", title: "Não foi possível retornar as respostas deste período", title_en: "Could not return replies for period", desc: "Could not return replies for period", desc_pt: "Não foi possível retornar as respostas deste período", type: "Temporary"},
  1008: {cls: "INTERNAL", title: "Não foi possível retornar a resposta", title_en: "Could not return reply", desc: "Could not return reply", desc_pt: "Não foi possível retornar a resposta", type: "Temporary"},
  1009: {cls: "INTERNAL", title: "Não foi possível retornar a resposta", title_en: "Could not return reply", desc: "Could not return reply", desc_pt: "Não foi possível retornar a resposta", type: "Temporary"},
  1010: {cls: "INTERNAL", title: "Não foi possível retornar múltiplas respostas", title_en: "Could not return multiple replies", desc: "Could not return multiple replies", desc_pt: "Não foi possível retornar múltiplas respostas", type: "Temporary"},
  1011: {cls: "VALIDATION", title: "Requisição inválida", title_en: "Invalid request", desc: "Invalid request", desc_pt: "Requisição inválida", type: "Permanent"},
  1012: {cls: "INTERNAL", title: "Não foi possível cancelar a mensagem", title_en: "Could not cancel message", desc: "Could not cancel message", desc_pt: "Não foi possível cancelar a mensagem", type: "Temporary"},
};
